// Generated by scripts/sync-hackmd.mjs.

export type ArticleCategory =
  | "security"
  | "quantum"
  | "machine-learning"
  | "engineering";

export interface ArticleSummary {
  id: string;
  slug: string;
  title: string;
  category: ArticleCategory;
  summary: string;
  featured: boolean;
  tags: string[];
  publishedAt: string;
  updatedAt: string;
  readingMinutes: number;
  sourceUrl: string | null;
}

export const articleIndex: ArticleSummary[] = [
  {
    "id": "zT4MQrfITAqyY6K5yq-AFQ",
    "slug": "isip-hs-ctf-writeup",
    "title": "ISIP-HS CTF Writeup",
    "category": "security",
    "summary": "ISIP-HS CTF 解題紀錄，涵蓋 Web、OSINT、雲端服務與基礎逆向題型。",
    "featured": true,
    "tags": [
      "security"
    ],
    "publishedAt": "2026-05-30",
    "updatedAt": "2026-06-09",
    "readingMinutes": 42,
    "sourceUrl": "https://hackmd.io/@SIRIUSW/Syk-3TDxfl"
  },
  {
    "id": "_Ybywtp2Q3yKEgqKjKAb5Q",
    "slug": "thjcc-ctf-2026-writeup",
    "title": "THJCC3 CTF Writeup",
    "category": "security",
    "summary": "THJCC CTF 2026 學生組第 16 名的賽後整理，記錄 Web 題目的觀察、嘗試與解法。",
    "featured": true,
    "tags": [
      "security"
    ],
    "publishedAt": "2026-02-27",
    "updatedAt": "2026-02-28",
    "readingMinutes": 8,
    "sourceUrl": "https://hackmd.io/@SIRIUSW/rJhPdXkYWe"
  },
  {
    "id": "74os89FeTbyFh-bZsb0x0Q",
    "slug": "fhctf-writeup",
    "title": "FhCTF Writeup",
    "category": "security",
    "summary": "FhCTF 的 Misc 與 Web 解題筆記，包含編碼、檔案上傳與 Python 題型。",
    "featured": false,
    "tags": [
      "security"
    ],
    "publishedAt": "2026-01-13",
    "updatedAt": "2026-01-13",
    "readingMinutes": 16,
    "sourceUrl": "https://hackmd.io/@SIRIUSW/SyJAr3XS-e"
  },
  {
    "id": "t14bIzXAQZ-Kz5DLGOp3NA",
    "slug": "quantum-rl-molecular-generation",
    "title": "Quantum Reinforcement Learning for Molecular Generation",
    "category": "quantum",
    "summary": "從 classical RL 基線到量子引導架構的分子生成研究紀錄，包含負結果與設計修正。",
    "featured": true,
    "tags": [
      "quantum"
    ],
    "publishedAt": "2025-12-12",
    "updatedAt": "2025-12-12",
    "readingMinutes": 14,
    "sourceUrl": "https://hackmd.io/@SIRIUSW/rJNGmYKzbe"
  },
  {
    "id": "AWZz0HPkQzetj9rFA7Ijhg",
    "slug": "eis-formulas",
    "title": "EIS 所有量的求法",
    "category": "engineering",
    "summary": "EIS 常用物理量、等效元件與阻抗公式的速查整理。",
    "featured": false,
    "tags": [
      "engineering"
    ],
    "publishedAt": "2025-11-28",
    "updatedAt": "2025-11-28",
    "readingMinutes": 3,
    "sourceUrl": "https://hackmd.io/@SIRIUSW/HJMt-OU--x"
  },
  {
    "id": "9qrJtz4AQYCYMGwOX2JIDA",
    "slug": "generative-quantum-eigensolver-notes",
    "title": "Generative Quantum Eigensolver（GQE）訓練筆記",
    "category": "quantum",
    "summary": "Generative Quantum Eigensolver 與 GPT-QE 的訓練流程、資料集與結果分析。",
    "featured": false,
    "tags": [
      "量子",
      "quantum"
    ],
    "publishedAt": "2025-10-16",
    "updatedAt": "2025-10-16",
    "readingMinutes": 3,
    "sourceUrl": "https://hackmd.io/@SIRIUSW/B13SDvC6lg"
  },
  {
    "id": "VpFsqdcaShCnc43Kuef0ew",
    "slug": "qml-adversarial-robustness",
    "title": "Adversarial Attacks and Robustness for Quantum Machine Learning 筆記",
    "category": "quantum",
    "summary": "量子機器學習模型的對抗性攻擊、PGD 實作與再訓練筆記。",
    "featured": false,
    "tags": [
      "量子",
      "quantum"
    ],
    "publishedAt": "2025-10-16",
    "updatedAt": "2025-10-16",
    "readingMinutes": 4,
    "sourceUrl": "https://hackmd.io/@SIRIUSW/B17KrD06ll"
  },
  {
    "id": "0-xJ1hvtSwaNoPa8o64PqQ",
    "slug": "quantum-image-generation",
    "title": "量子圖片生成技術：PennyLane與NVIDIA實作與科學原理整理",
    "category": "quantum",
    "summary": "量子 GAN、Quanvolution 與 Born Machine 的原理，以及 PennyLane、NVIDIA 實作脈絡。",
    "featured": false,
    "tags": [
      "quantum"
    ],
    "publishedAt": "2025-10-10",
    "updatedAt": "2025-10-10",
    "readingMinutes": 10,
    "sourceUrl": "https://hackmd.io/@SIRIUSW/S1Xfb48pxx"
  },
  {
    "id": "69GVRhsMRN-27gVLfpYp3g",
    "slug": "quantum-glossary",
    "title": "量子相關專有名詞說明",
    "category": "quantum",
    "summary": "從 qubit、量子閘到 VQE、QAOA 的量子運算名詞筆記。",
    "featured": false,
    "tags": [
      "量子",
      "quantum"
    ],
    "publishedAt": "2025-09-28",
    "updatedAt": "2025-09-28",
    "readingMinutes": 3,
    "sourceUrl": "https://hackmd.io/@SIRIUSW/H1clt9Lnee"
  },
  {
    "id": "VJaQLtnNQU2ucbl6t3Gv0Q",
    "slug": "random-forest",
    "title": "隨機森林（Random Forest）",
    "category": "machine-learning",
    "summary": "隨機森林的 Bagging、隨機特徵選取、超參數與實務限制。",
    "featured": false,
    "tags": [
      "演算法",
      "machine-learning"
    ],
    "publishedAt": "2025-09-19",
    "updatedAt": "2025-09-19",
    "readingMinutes": 2,
    "sourceUrl": "https://hackmd.io/@SIRIUSW/rkx7h0coll"
  },
  {
    "id": "OrA7ltP2QoGHLKYKayj1Vg",
    "slug": "k-means",
    "title": "K-means（K-means Clustering）",
    "category": "machine-learning",
    "summary": "K-means 的迭代流程、SSE 目標、初始化與分群實務。",
    "featured": false,
    "tags": [
      "演算法",
      "machine-learning"
    ],
    "publishedAt": "2025-09-19",
    "updatedAt": "2025-09-19",
    "readingMinutes": 2,
    "sourceUrl": "https://hackmd.io/@SIRIUSW/ryK9a05ile"
  },
  {
    "id": "RfsDXMTyRSWo-MWFijIPfw",
    "slug": "knn",
    "title": "K 近鄰（K-Nearest Neighbors, KNN）",
    "category": "machine-learning",
    "summary": "KNN 的距離度量、鄰居投票、特徵縮放與使用情境。",
    "featured": false,
    "tags": [
      "演算法",
      "machine-learning"
    ],
    "publishedAt": "2025-09-19",
    "updatedAt": "2025-09-19",
    "readingMinutes": 1,
    "sourceUrl": "https://hackmd.io/@SIRIUSW/rJ28pAcjgx"
  },
  {
    "id": "WBy5psEvRJiezyA7fj7akg",
    "slug": "support-vector-machine",
    "title": "支援向量機（SVM, Support Vector Machine）",
    "category": "machine-learning",
    "summary": "SVM 的最大間隔、核函數、超參數與小樣本應用。",
    "featured": false,
    "tags": [
      "演算法",
      "machine-learning"
    ],
    "publishedAt": "2025-09-19",
    "updatedAt": "2025-09-19",
    "readingMinutes": 2,
    "sourceUrl": "https://hackmd.io/@SIRIUSW/HkHSa09sxl"
  },
  {
    "id": "30_zMxRZRay9ix_3gNyaKA",
    "slug": "multinomial-logistic-regression",
    "title": "多元 / 多類邏輯斯回歸（Logistic Regression / Multinomial）",
    "category": "machine-learning",
    "summary": "二元與多類邏輯斯回歸的機率模型、損失函數與可解釋性。",
    "featured": false,
    "tags": [
      "演算法",
      "machine-learning"
    ],
    "publishedAt": "2025-09-19",
    "updatedAt": "2025-09-19",
    "readingMinutes": 2,
    "sourceUrl": "https://hackmd.io/@SIRIUSW/ByOQT05jlg"
  },
  {
    "id": "N5b-OFP_R3uUNPOEnxljHg",
    "slug": "shors-algorithm",
    "title": "Shor’s Algorithm",
    "category": "quantum",
    "summary": "Shor 演算法的週期尋找、數學流程、密碼學影響與實機挑戰。",
    "featured": false,
    "tags": [
      "演算法",
      "量子",
      "quantum"
    ],
    "publishedAt": "2025-09-19",
    "updatedAt": "2025-09-19",
    "readingMinutes": 2,
    "sourceUrl": "https://hackmd.io/@SIRIUSW/H1C69aqixx"
  },
  {
    "id": "2UY43xxTTaSo08XG7KqLGA",
    "slug": "ais3-junior-team-project",
    "title": "AIS3 JR 專題 第8組",
    "category": "security",
    "summary": "AIS3 Junior 第 8 組專題紀錄：WordPress 漏洞環境、CVE 重現與分工實作。",
    "featured": false,
    "tags": [
      "security"
    ],
    "publishedAt": "2025-08-10",
    "updatedAt": "2025-08-14",
    "readingMinutes": 5,
    "sourceUrl": "https://hackmd.io/@SIRIUSW/B1XKsUIOge"
  },
  {
    "id": "XSy1iWlLT5-TD7mfUoZRRw",
    "slug": "web-ctf-basic-writeup",
    "title": "Web CTF Basic 作業 Writeup",
    "category": "security",
    "summary": "AIS3 Junior Web CTF 基礎作業，從 HTTP 方法、Cookie 到原始碼與注入題型。",
    "featured": false,
    "tags": [
      "security"
    ],
    "publishedAt": "2025-08-10",
    "updatedAt": "2025-08-12",
    "readingMinutes": 9,
    "sourceUrl": "https://hackmd.io/@SIRIUSW/H1taXRrOgg"
  }
];
